/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserId = IDL.Text;
export const ApplicationId = IDL.Text;
export const ApplicationStatus = IDL.Variant({
  'UnderReview' : IDL.Null,
  'Approved' : IDL.Null,
  'Draft' : IDL.Null,
  'Rejected' : IDL.Null,
  'Submitted' : IDL.Null,
  'PendingApproval' : IDL.Null,
  'Escalated' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const Document = IDL.Record({
  'id' : IDL.Text,
  'url' : IDL.Text,
  'ocrExtracted' : IDL.Bool,
  'name' : IDL.Text,
  'aiConfidence' : IDL.Opt(IDL.Float64),
  'docType' : IDL.Text,
  'uploadedAt' : Timestamp,
});
export const ProgramType = IDL.Variant({
  'CMEReimbursement' : IDL.Null,
  'DependentTuition' : IDL.Null,
  'TuitionReimbursement' : IDL.Null,
  'MMCScholarship' : IDL.Null,
});
export const Application = IDL.Record({
  'id' : ApplicationId,
  'status' : ApplicationStatus,
  'credits' : IDL.Nat,
  'documents' : IDL.Vec(Document),
  'institution' : IDL.Text,
  'createdAt' : Timestamp,
  'submittedAt' : IDL.Opt(Timestamp),
  'updatedAt' : Timestamp,
  'employeeId' : UserId,
  'programType' : ProgramType,
  'courseTitle' : IDL.Text,
  'amount' : IDL.Float64,
});
export const AuditEntryId = IDL.Text;
export const AuditEntry = IDL.Record({
  'id' : AuditEntryId,
  'action' : IDL.Text,
  'entityId' : IDL.Text,
  'performedBy' : IDL.Text,
  'timestamp' : Timestamp,
  'details' : IDL.Text,
});
export const CaseId = IDL.Text;
export const SlaStatus = IDL.Variant({
  'Overdue' : IDL.Null,
  'OnTrack' : IDL.Null,
  'AtRisk' : IDL.Null,
});
export const CaseItem = IDL.Record({
  'id' : CaseId,
  'submittedDate' : Timestamp,
  'status' : ApplicationStatus,
  'employeeName' : IDL.Text,
  'assignedHR' : IDL.Text,
  'applicationId' : ApplicationId,
  'escalated' : IDL.Bool,
  'dueDate' : Timestamp,
  'aiConfidence' : IDL.Float64,
  'employeeId' : UserId,
  'programType' : ProgramType,
  'slaStatus' : SlaStatus,
});
export const TuitionBalance = IDL.Record({
  'total' : IDL.Float64,
  'remaining' : IDL.Float64,
});
export const CreditBalance = IDL.Record({
  'total' : IDL.Nat,
  'remaining' : IDL.Nat,
});
export const Employee = IDL.Record({
  'id' : UserId,
  'title' : IDL.Text,
  'hireDate' : Timestamp,
  'name' : IDL.Text,
  'tuitionBalance' : TuitionBalance,
  'email' : IDL.Text,
  'employeeId' : IDL.Text,
  'creditBalance' : CreditBalance,
  'managerId' : IDL.Opt(UserId),
  'phone' : IDL.Text,
  'department' : IDL.Text,
});
export const NotificationId = IDL.Text;
export const NotificationType = IDL.Variant({
  'Info' : IDL.Null,
  'Deadline' : IDL.Null,
  'Approval' : IDL.Null,
  'Warning' : IDL.Null,
});
export const Notification = IDL.Record({
  'id' : NotificationId,
  'title' : IDL.Text,
  'notifType' : NotificationType,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'read' : IDL.Bool,
  'message' : IDL.Text,
});
export const ApprovalStatus = IDL.Variant({
  'Approved' : IDL.Null,
  'Rejected' : IDL.Null,
  'Escalated' : IDL.Null,
  'Pending' : IDL.Null,
});
export const ApprovalItem = IDL.Record({
  'id' : IDL.Text,
  'submittedDate' : Timestamp,
  'status' : ApprovalStatus,
  'employeeName' : IDL.Text,
  'applicationId' : ApplicationId,
  'dueDate' : Timestamp,
  'employeeId' : UserId,
  'aiSummary' : IDL.Text,
  'programType' : ProgramType,
  'amount' : IDL.Float64,
});
export const ProgramId = IDL.Text;
export const Program = IDL.Record({
  'id' : ProgramId,
  'maxAmount' : IDL.Float64,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'maxCredits' : IDL.Nat,
  'eligibilityRules' : IDL.Vec(IDL.Text),
});
export const ApplicationInput = IDL.Record({
  'credits' : IDL.Nat,
  'institution' : IDL.Text,
  'employeeId' : UserId,
  'programType' : ProgramType,
  'courseTitle' : IDL.Text,
  'amount' : IDL.Float64,
});

export const idlService = IDL.Service({
  'approveApplication' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'escalateApplication' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getApplications' : IDL.Func([UserId], [IDL.Vec(Application)], ['query']),
  'getAuditLog' : IDL.Func([], [IDL.Vec(AuditEntry)], ['query']),
  'getCaseQueue' : IDL.Func([], [IDL.Vec(CaseItem)], ['query']),
  'getEmployee' : IDL.Func([UserId], [IDL.Opt(Employee)], ['query']),
  'getNotifications' : IDL.Func([UserId], [IDL.Vec(Notification)], ['query']),
  'getPendingApprovals' : IDL.Func([], [IDL.Vec(ApprovalItem)], ['query']),
  'getPrograms' : IDL.Func([], [IDL.Vec(Program)], ['query']),
  'markNotificationRead' : IDL.Func([NotificationId], [], []),
  'rejectApplication' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'submitApplication' : IDL.Func([ApplicationInput], [ApplicationId], []),
  'updateApplicationStatus' : IDL.Func(
      [ApplicationId, ApplicationStatus],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserId = IDL.Text;
  const ApplicationId = IDL.Text;
  const ApplicationStatus = IDL.Variant({
    'UnderReview' : IDL.Null,
    'Approved' : IDL.Null,
    'Draft' : IDL.Null,
    'Rejected' : IDL.Null,
    'Submitted' : IDL.Null,
    'PendingApproval' : IDL.Null,
    'Escalated' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const Document = IDL.Record({
    'id' : IDL.Text,
    'url' : IDL.Text,
    'ocrExtracted' : IDL.Bool,
    'name' : IDL.Text,
    'aiConfidence' : IDL.Opt(IDL.Float64),
    'docType' : IDL.Text,
    'uploadedAt' : Timestamp,
  });
  const ProgramType = IDL.Variant({
    'CMEReimbursement' : IDL.Null,
    'DependentTuition' : IDL.Null,
    'TuitionReimbursement' : IDL.Null,
    'MMCScholarship' : IDL.Null,
  });
  const Application = IDL.Record({
    'id' : ApplicationId,
    'status' : ApplicationStatus,
    'credits' : IDL.Nat,
    'documents' : IDL.Vec(Document),
    'institution' : IDL.Text,
    'createdAt' : Timestamp,
    'submittedAt' : IDL.Opt(Timestamp),
    'updatedAt' : Timestamp,
    'employeeId' : UserId,
    'programType' : ProgramType,
    'courseTitle' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const AuditEntryId = IDL.Text;
  const AuditEntry = IDL.Record({
    'id' : AuditEntryId,
    'action' : IDL.Text,
    'entityId' : IDL.Text,
    'performedBy' : IDL.Text,
    'timestamp' : Timestamp,
    'details' : IDL.Text,
  });
  const CaseId = IDL.Text;
  const SlaStatus = IDL.Variant({
    'Overdue' : IDL.Null,
    'OnTrack' : IDL.Null,
    'AtRisk' : IDL.Null,
  });
  const CaseItem = IDL.Record({
    'id' : CaseId,
    'submittedDate' : Timestamp,
    'status' : ApplicationStatus,
    'employeeName' : IDL.Text,
    'assignedHR' : IDL.Text,
    'applicationId' : ApplicationId,
    'escalated' : IDL.Bool,
    'dueDate' : Timestamp,
    'aiConfidence' : IDL.Float64,
    'employeeId' : UserId,
    'programType' : ProgramType,
    'slaStatus' : SlaStatus,
  });
  const TuitionBalance = IDL.Record({
    'total' : IDL.Float64,
    'remaining' : IDL.Float64,
  });
  const CreditBalance = IDL.Record({
    'total' : IDL.Nat,
    'remaining' : IDL.Nat,
  });
  const Employee = IDL.Record({
    'id' : UserId,
    'title' : IDL.Text,
    'hireDate' : Timestamp,
    'name' : IDL.Text,
    'tuitionBalance' : TuitionBalance,
    'email' : IDL.Text,
    'employeeId' : IDL.Text,
    'creditBalance' : CreditBalance,
    'managerId' : IDL.Opt(UserId),
    'phone' : IDL.Text,
    'department' : IDL.Text,
  });
  const NotificationId = IDL.Text;
  const NotificationType = IDL.Variant({
    'Info' : IDL.Null,
    'Deadline' : IDL.Null,
    'Approval' : IDL.Null,
    'Warning' : IDL.Null,
  });
  const Notification = IDL.Record({
    'id' : NotificationId,
    'title' : IDL.Text,
    'notifType' : NotificationType,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'read' : IDL.Bool,
    'message' : IDL.Text,
  });
  const ApprovalStatus = IDL.Variant({
    'Approved' : IDL.Null,
    'Rejected' : IDL.Null,
    'Escalated' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const ApprovalItem = IDL.Record({
    'id' : IDL.Text,
    'submittedDate' : Timestamp,
    'status' : ApprovalStatus,
    'employeeName' : IDL.Text,
    'applicationId' : ApplicationId,
    'dueDate' : Timestamp,
    'employeeId' : UserId,
    'aiSummary' : IDL.Text,
    'programType' : ProgramType,
    'amount' : IDL.Float64,
  });
  const ProgramId = IDL.Text;
  const Program = IDL.Record({
    'id' : ProgramId,
    'maxAmount' : IDL.Float64,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'maxCredits' : IDL.Nat,
    'eligibilityRules' : IDL.Vec(IDL.Text),
  });
  const ApplicationInput = IDL.Record({
    'credits' : IDL.Nat,
    'institution' : IDL.Text,
    'employeeId' : UserId,
    'programType' : ProgramType,
    'courseTitle' : IDL.Text,
    'amount' : IDL.Float64,
  });
  
  return IDL.Service({
    'approveApplication' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'escalateApplication' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getApplications' : IDL.Func([UserId], [IDL.Vec(Application)], ['query']),
    'getAuditLog' : IDL.Func([], [IDL.Vec(AuditEntry)], ['query']),
    'getCaseQueue' : IDL.Func([], [IDL.Vec(CaseItem)], ['query']),
    'getEmployee' : IDL.Func([UserId], [IDL.Opt(Employee)], ['query']),
    'getNotifications' : IDL.Func([UserId], [IDL.Vec(Notification)], ['query']),
    'getPendingApprovals' : IDL.Func([], [IDL.Vec(ApprovalItem)], ['query']),
    'getPrograms' : IDL.Func([], [IDL.Vec(Program)], ['query']),
    'markNotificationRead' : IDL.Func([NotificationId], [], []),
    'rejectApplication' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'submitApplication' : IDL.Func([ApplicationInput], [ApplicationId], []),
    'updateApplicationStatus' : IDL.Func(
        [ApplicationId, ApplicationStatus],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };