/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Application {
  'id' : ApplicationId,
  'status' : ApplicationStatus,
  'credits' : bigint,
  'documents' : Array<Document>,
  'institution' : string,
  'createdAt' : Timestamp,
  'submittedAt' : [] | [Timestamp],
  'updatedAt' : Timestamp,
  'employeeId' : UserId,
  'programType' : ProgramType,
  'courseTitle' : string,
  'amount' : number,
}
export type ApplicationId = string;
export interface ApplicationInput {
  'credits' : bigint,
  'institution' : string,
  'employeeId' : UserId,
  'programType' : ProgramType,
  'courseTitle' : string,
  'amount' : number,
}
export type ApplicationStatus = { 'UnderReview' : null } |
  { 'Approved' : null } |
  { 'Draft' : null } |
  { 'Rejected' : null } |
  { 'Submitted' : null } |
  { 'PendingApproval' : null } |
  { 'Escalated' : null };
export interface ApprovalItem {
  'id' : string,
  'submittedDate' : Timestamp,
  'status' : ApprovalStatus,
  'employeeName' : string,
  'applicationId' : ApplicationId,
  'dueDate' : Timestamp,
  'employeeId' : UserId,
  'aiSummary' : string,
  'programType' : ProgramType,
  'amount' : number,
}
export type ApprovalStatus = { 'Approved' : null } |
  { 'Rejected' : null } |
  { 'Escalated' : null } |
  { 'Pending' : null };
export interface AuditEntry {
  'id' : AuditEntryId,
  'action' : string,
  'entityId' : string,
  'performedBy' : string,
  'timestamp' : Timestamp,
  'details' : string,
}
export type AuditEntryId = string;
export type CaseId = string;
export interface CaseItem {
  'id' : CaseId,
  'submittedDate' : Timestamp,
  'status' : ApplicationStatus,
  'employeeName' : string,
  'assignedHR' : string,
  'applicationId' : ApplicationId,
  'escalated' : boolean,
  'dueDate' : Timestamp,
  'aiConfidence' : number,
  'employeeId' : UserId,
  'programType' : ProgramType,
  'slaStatus' : SlaStatus,
}
export interface CreditBalance { 'total' : bigint, 'remaining' : bigint }
export interface Document {
  'id' : string,
  'url' : string,
  'ocrExtracted' : boolean,
  'name' : string,
  'aiConfidence' : [] | [number],
  'docType' : string,
  'uploadedAt' : Timestamp,
}
export interface Employee {
  'id' : UserId,
  'title' : string,
  'hireDate' : Timestamp,
  'name' : string,
  'tuitionBalance' : TuitionBalance,
  'email' : string,
  'employeeId' : string,
  'creditBalance' : CreditBalance,
  'managerId' : [] | [UserId],
  'phone' : string,
  'department' : string,
}
export interface Notification {
  'id' : NotificationId,
  'title' : string,
  'notifType' : NotificationType,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'read' : boolean,
  'message' : string,
}
export type NotificationId = string;
export type NotificationType = { 'Info' : null } |
  { 'Deadline' : null } |
  { 'Approval' : null } |
  { 'Warning' : null };
export interface Program {
  'id' : ProgramId,
  'maxAmount' : number,
  'name' : string,
  'description' : string,
  'maxCredits' : bigint,
  'eligibilityRules' : Array<string>,
}
export type ProgramId = string;
export type ProgramType = { 'CMEReimbursement' : null } |
  { 'DependentTuition' : null } |
  { 'TuitionReimbursement' : null } |
  { 'MMCScholarship' : null };
export type SlaStatus = { 'Overdue' : null } |
  { 'OnTrack' : null } |
  { 'AtRisk' : null };
export type Timestamp = bigint;
export interface TuitionBalance { 'total' : number, 'remaining' : number }
export type UserId = string;
export interface _SERVICE {
  'approveApplication' : ActorMethod<[string, string], undefined>,
  'escalateApplication' : ActorMethod<[string, string], undefined>,
  'getApplications' : ActorMethod<[UserId], Array<Application>>,
  'getAuditLog' : ActorMethod<[], Array<AuditEntry>>,
  'getCaseQueue' : ActorMethod<[], Array<CaseItem>>,
  'getEmployee' : ActorMethod<[UserId], [] | [Employee]>,
  'getNotifications' : ActorMethod<[UserId], Array<Notification>>,
  'getPendingApprovals' : ActorMethod<[], Array<ApprovalItem>>,
  'getPrograms' : ActorMethod<[], Array<Program>>,
  'markNotificationRead' : ActorMethod<[NotificationId], undefined>,
  'rejectApplication' : ActorMethod<[string, string], undefined>,
  'submitApplication' : ActorMethod<[ApplicationInput], ApplicationId>,
  'updateApplicationStatus' : ActorMethod<
    [ApplicationId, ApplicationStatus],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];